import type { PresetDef } from "../types";

/**
 * Particle Flow — a GPU compute-particle system. 120k particles are advanced
 * every frame by a curl-noise flow field plus audio forces (bass amplifies the
 * flow, kicks fire per-particle radial bursts), then drawn as additive sprites
 * that bloom into glowing streams. Unlike the fragment-shader "Particles"
 * preset, these are a real simulation with momentum and emergent structure.
 *
 * Driven by the renderer's built-in particle path (PARTICLE_SIM_WGSL +
 * PARTICLE_DRAW_WGSL); the `wgsl` fragment body below is an unused stub.
 * Params map by key into the sim uniform
 * (see PARTICLE_PARAM_KEYS). Deterministic: seeded init, fixed 60 Hz sim rate
 * keyed to track time, no RNG.
 */
export const particleFlow: PresetDef = {
  id: "particle-flow",
  name: "Particle Flow",
  description:
    "120k GPU particles swept through a curl-noise flow field — bass drives the current, kicks scatter them, additive glow blooms the streams. The looks span the sim's whole range, from a bound spiral galaxy to a full firehose.",
  particles: { count: 120_000 },
  styles: [
    // Flow — the defaults — a curl-noise current with beat scatter.
    { id: "flow", name: "Flow", values: {} },
    // Galaxy — swirl plus centre pull binds the field into a spiral, not a fountain.
    {
      id: "galaxy",
      name: "Galaxy",
      values: {
        hue: 42,
        hueSpread: 90,
        swirl: 1.7,
        gravity: 1.05,
        flowStrength: 0.25,
        flowScale: 0.7,
        damping: 0.985,
        spawnRadius: 0.1,
        size: 0.006,
        brightness: 0.55,
        density: 0.6,
        audioFlow: 1.2,
        beatBurst: 0.6,
        sizePulse: 0.3,
        speedColor: 0.4,
        sat: 0.76,
      },
    },
    // Ink Drop — few big dim slow particles, high damping: pigment spreading in water.
    {
      id: "inkDrop",
      name: "Ink Drop",
      values: {
        hue: 228,
        hueSpread: 25,
        size: 0.024,
        brightness: 0.2,
        density: 0.35,
        flowStrength: 0.45,
        swirl: 0.15,
        flowScale: 0.7,
        damping: 0.985,
        audioFlow: 0.6,
        beatBurst: 0.7,
        sat: 0.28,
        speedColor: 0.08,
        spawnRadius: 0.3,
        sizePulse: 0.2,
      },
    },
    // Solar Wind — high flow and bass drive from a tiny spawn disc — a streaming corona.
    {
      id: "solarWind",
      name: "Solar Wind",
      values: {
        hue: 24,
        flowStrength: 1.85,
        swirl: 0.1,
        flowScale: 1.2,
        damping: 0.94,
        gravity: 0,
        audioFlow: 3.6,
        beatBurst: 1.3,
        size: 0.005,
        brightness: 0.65,
        density: 0.7,
        speedColor: 0.4,
        sat: 0.9,
        spawnRadius: 0.08,
        sizePulse: 0.9,
      },
    },
    // Blizzard — every particle drawn, fine eddies, near-white: driven snow.
    {
      id: "blizzard",
      name: "Blizzard",
      values: {
        hue: 202,
        hueSpread: 20,
        sat: 0.14,
        flowStrength: 1.6,
        flowScale: 3.3,
        damping: 0.9,
        density: 1,
        size: 0.003,
        brightness: 0.9,
        beatBurst: 0.9,
        audioFlow: 2.4,
        speedColor: 0.14,
        spawnRadius: 0.6,
        sizePulse: 0.3,
        gravity: 0.1,
      },
    },
    // Firehose — max burst, low damping, strong gravity — chaos that keeps falling back.
    {
      id: "firehose",
      name: "Firehose",
      values: {
        hue: 12,
        hueSpread: 55,
        flowStrength: 2,
        swirl: 0.25,
        beatBurst: 3,
        size: 0.005,
        brightness: 0.95,
        flowScale: 2.5,
        damping: 0.85,
        gravity: 0.95,
        audioFlow: 3.8,
        speedColor: 0.28,
        spawnRadius: 0.04,
        density: 0.85,
        sizePulse: 1.4,
        sat: 0.9,
      },
    },
    // Filaments — editorial. 15% density, tiny points, high damping: drawn streamlines.
    {
      id: "filaments",
      name: "Filaments",
      values: {
        hue: 190,
        hueSpread: 15,
        density: 0.15,
        size: 0.005,
        brightness: 0.7,
        damping: 0.99,
        flowStrength: 0.8,
        flowScale: 1.1,
        swirl: 0.05,
        gravity: 0.15,
        audioFlow: 1,
        beatBurst: 0.4,
        sat: 0.36,
        speedColor: 0.1,
        spawnRadius: 0.4,
        sizePulse: 0.15,
      },
    },
  ],
  params: [
    {
      key: "hue",
      label: "Hue",
      group: "color",
      control: "hue",
      min: 0,
      max: 360,
      step: 1,
      default: 200,
      hint: "Base particle color",
    },
    {
      key: "flowStrength",
      label: "Flow",
      group: "motion",
      min: 0,
      max: 2,
      step: 0.05,
      default: 1,
      hint: "Strength of the curl-noise current that sweeps the particles",
    },
    {
      key: "swirl",
      label: "Swirl",
      group: "motion",
      min: 0,
      max: 2,
      step: 0.05,
      default: 0.3,
      hint: "Rotational pull around the center — high values wind the field into a spiral",
    },
    {
      key: "beatBurst",
      label: "Beat burst",
      group: "reaction",
      min: 0,
      max: 3,
      step: 0.05,
      default: 1.4,
      hint: "How hard kicks scatter the particles outward",
    },
    {
      key: "size",
      label: "Particle size",
      group: "shape",
      min: 0.002,
      max: 0.03,
      step: 0.001,
      default: 0.007,
      hint: "On-screen size of each particle",
    },
    {
      key: "brightness",
      label: "Brightness",
      group: "glow",
      min: 0.1,
      max: 1.5,
      step: 0.05,
      default: 0.62,
      hint: "Additive glow of each particle",
    },
    {
      key: "density",
      label: "Density",
      group: "shape",
      min: 0.1,
      max: 1,
      step: 0.05,
      default: 0.45,
      hint: "Fraction of the 120k particles drawn — lower shows the flow structure, 1.0 packs it solid",
    },
  ],
  advanced: [
    {
      key: "flowScale",
      label: "Flow scale",
      group: "motion",
      min: 0.3,
      max: 4,
      step: 0.1,
      default: 1.6,
      hint: "Spatial frequency of the flow field — higher = finer eddies",
    },
    {
      key: "damping",
      label: "Damping",
      group: "motion",
      min: 0.8,
      max: 0.99,
      step: 0.005,
      default: 0.95,
      hint: "Velocity retained each step — higher = longer, smoother streams",
    },
    {
      key: "gravity",
      label: "Center pull",
      group: "motion",
      min: 0,
      max: 1.5,
      step: 0.05,
      default: 0.05,
      hint: "Pull back toward the center — balances the outward fountain",
    },
    {
      key: "audioFlow",
      label: "Bass drive",
      group: "reaction",
      min: 0,
      max: 4,
      step: 0.1,
      default: 2,
      hint: "How much bass amplifies the flow current",
    },
    {
      key: "sizePulse",
      label: "Speed size",
      group: "shape",
      min: 0,
      max: 2,
      step: 0.05,
      default: 0.5,
      hint: "Faster particles grow larger — emphasizes the fast streamlines",
    },
    {
      key: "hueSpread",
      label: "Hue spread",
      group: "color",
      min: 0,
      max: 180,
      step: 5,
      default: 50,
      hint: "Per-particle color variation",
    },
    {
      key: "speedColor",
      label: "Speed color",
      group: "color",
      min: 0,
      max: 1,
      step: 0.02,
      default: 0.3,
      hint: "Shifts color by particle speed",
    },
    {
      key: "sat",
      label: "Saturation",
      group: "color",
      min: 0,
      max: 1,
      step: 0.02,
      default: 0.8,
      hint: "Color saturation",
    },
    {
      key: "spawnRadius",
      label: "Respawn radius",
      group: "shape",
      min: 0.02,
      max: 0.6,
      step: 0.02,
      default: 0.55,
      hint: "How near the center particles respawn after drifting off-frame",
    },
  ],
  // Unused: particle presets render via the built-in compute path. Stub keeps
  // the shared fragment pipeline compiling.
  wgsl: /* wgsl */ `
fn preset(uv: vec2f) -> vec4f { return vec4f(0.0); }
`,
};
