import type { ParamValues } from "../src/render/types";
import type { SyncSettings } from "../src/audio/types";
import type { UserPreset } from "../src/state/userPresets";

/**
 * Track C2 (look pass 2) and C3 (Aurora + the seeds Track B unlocked).
 *
 * A LOOK carries params and sync ONLY — that is the format's design, not a
 * limitation to route around; the full-capability showcase is what the C1
 * themes are for. So the deepening axes available here are exactly two:
 *
 *  1. the parameters Track B added to a mode, which every one of the nine
 *     live looks predates, and
 *  2. `sync`, which the `.bfpreset` envelope has always supported and which
 *     NONE of the nine carries — every one of them plays at the app's default
 *     feel regardless of what the look is trying to be.
 *
 * C2 entries are therefore expressed as a DELTA over the seed exactly as it
 * is authored today (`base`), not as a rewrite: `candidates.test.ts` reads
 * `scripts/gallery-seed-shots.mjs` and asserts every `base` below still equals
 * the live seed, so a delta can never be proposed against a stale copy. The
 * emitted `.bfpreset` is `{...base, ...delta}` — a complete look, because that
 * is what the file format is — but the veto sheet shows the owner only the
 * delta keys.
 *
 * C3 entries have no `base`: they are new looks for modes with no gallery
 * entry at all, and each exists because Track B made a visual reachable that
 * simply was not there before.
 */

export interface LookEntry {
  /** Gallery id. Existing for C2 (content re-pins under the same id), new for C3. */
  id: string;
  name: string;
  presetId: string;
  track: "C2" | "C3";
  /** The seed as authored today. Present iff `track` is "C2". */
  base?: ParamValues;
  /** C2: only what changes. C3: the whole look. */
  delta: ParamValues;
  /** Every entry commits to a sync feel — none of the nine does today. */
  sync: SyncSettings;
  /** Registry description. C2 keeps the seed's own words unless the delta
   * changes what the entry actually is. */
  description: string;
  /** Why this delta, in one paragraph, for the veto sheet. */
  note: string;
}

/** Fixed so re-emitting the files is byte-stable. */
const CREATED_AT = "2026-08-14T00:00:00.000Z";

export function toUserPreset(e: LookEntry): UserPreset {
  return {
    // Deliberately derived, never `newUserPresetId()`: a random id would make
    // every re-emission a diff. parseUserPreset replaces it on import anyway.
    id: `up-trackc-${e.id}`,
    name: e.name,
    presetId: e.presetId,
    params: { ...(e.base ?? {}), ...e.delta },
    sync: e.sync,
    createdAt: CREATED_AT,
  };
}

export const LOOK_ENTRIES: LookEntry[] = [
  // ---------------------------------------------------------------- C2 ----
  {
    id: "prism-cathedral",
    name: "Prism Cathedral",
    presetId: "echo-trails",
    track: "C2",
    description:
      "A rose window built from your music: six-fold mirrored echoes refract every beat into stained-glass petals that bloom and fade.",
    base: {
      hue: 285,
      mirror: 6,
      sides: 6,
      echoHue: 0.7,
      hueSpin: 0.5,
      hueDrift: 0.3,
      decay: 0.95,
      zoom: 0.3,
      swirl: 0.18,
      radius: 0.3,
      thick: 0.018,
      react: 0.12,
      inject: 0.4,
      beatStar: 0.7,
      kickFlash: 0.12,
      beatZoom: 0.2,
      flowSwirl: 0.15,
      vignette: 0.45,
    },
    delta: { source: 1, warp: 2, thick: 0.02, flowSwirl: 0.16 },
    sync: { mode: "kick", smooth: 0.32, attack: 0.03, release: 0.5 },
    note: "The look's own description promises stained-glass petals, but the accumulator could only eat a ring when it was authored — every echo was the same closed loop, six times over. `source: 1` feeds it the star shape instead, so the lobes it already asks for (sides 6) become points of light rather than segments of a circle, and `warp: 2` swaps the swirl field for the radial wave, which is what 'refract' actually looks like. `thick` and `flowSwirl` move one step each only because the authored values sit off their spec grids.",
  },
  {
    id: "orchid-glass",
    name: "Orchid Glass",
    presetId: "metaballs",
    track: "C2",
    description:
      "Violet glass in a slow boil — glossy orbs merge and split with the bassline, lit like studio chrome.",
    base: {
      hue: 45,
      hueField: 18,
      count: 4,
      size: 0.16,
      speed: 0.22,
      gloss: 0.95,
      glow: 0.45,
      innerGrad: 0.5,
      rimStart: 0.5,
      threshold: 1.15,
      energyGrow: 1,
      radiusBand: 0.6,
      radiusFloor: 0.8,
      beatSwell: 0.28,
      beatBright: 0.12,
      squash: 0.2,
      orbitX: 0.24,
      orbitY: 0.2,
      lightAngle: 55,
      bgLevel: 0.008,
      vignette: 0.5,
    },
    delta: {
      environment: 1,
      bassWeight: 0.45,
      eccentric: 0.28,
      speed: 0.2,
      gloss: 0.96,
      threshold: 1.14,
      bgLevel: 0.01,
    },
    sync: { mode: "bass", smooth: 0.5, attack: 0.18, release: 0.65 },
    note: "The description says 'lit like studio chrome' and the look renders in the Void, because the gloss environment did not exist yet — `environment: 1` is the entry finally being the thing it claims to be. `bassWeight` makes 'merge and split with the bassline' literal instead of a general energy swell, and `eccentric` gives each blob its own squash so they read as glass rather than as marbles. Lava smear is DECLINED on purpose: enabling it moves the mode onto the high-precision trail path, which is a performance reclassification, not a look decision. `speed`, `gloss`, `threshold` and `bgLevel` move by one step each only to land on their grids.",
  },
  {
    id: "abyssal-bloom",
    name: "Abyssal Bloom",
    presetId: "nebula",
    track: "C2",
    description:
      "Bioluminescence from the deep — an emerald kaleidoscope flower that ripples open on every kick and glitters like plankton.",
    base: {
      hue: 210,
      hueRange: 40,
      midHueShift: 0,
      kaleido: 7,
      scale: 2.6,
      warp: 2.2,
      flow: 0.08,
      contrast: 0.95,
      saturation: 0.7,
      depth: 0.4,
      sparkle: 0.7,
      sparkleScale: 26,
      sparkleSharp: 36,
      hotCore: 1.2,
      brightFloor: 0.06,
      bassBright: 0.3,
      beatRipple: 0.4,
      rippleWidth: 24,
      beatBloom: 0.1,
      driveGlow: 0.08,
      spin: 0.2,
      vignette: 0.6,
    },
    delta: {
      saturation: 0.94,
      duo: 0.55,
      hue2: 285,
      stars: 0.35,
      windStrength: 0.22,
      windAngle: 190,
    },
    sync: { mode: "bass", smooth: 0.55, attack: 0.2, release: 0.7 },
    note: "This one carries a real BUG, not just headroom. The seed was authored before schema v14 changed what nebula's `saturation` means (raw 0..1 palette mix -> a 0..2 scaler the shader folds onto the old authored point), and `.bfpreset` is one of the three stores that documentedly cannot ride that migration — so the authored 0.7 is read today as a 0.7 SCALER and the look renders about a quarter flatter than it was approved at. 0.94 is the exact equal-render value (0.7 / 0.75) snapped to the 0.02 grid. On top of that: `duo` + `hue2` give the deep its second palette anchor (teal core, magenta rim — the emission-nebula split a single ramp cannot reach), `stars` puts a parallax field behind the clouds, and `windStrength`/`windAngle` give the water a direction, which is what makes an abyss read as current rather than as wallpaper.",
  },
  {
    id: "solar-cascade",
    name: "Solar Cascade",
    presetId: "particle-flow",
    track: "C2",
    description:
      "120k embers in a golden spiral — the galaxy tightens as the track drives and erupts outward on every kick.",
    base: {
      hue: 40,
      hueSpread: 30,
      swirl: 1.2,
      gravity: 0.6,
      flowStrength: 0.9,
      flowScale: 1,
      damping: 0.965,
      spawnRadius: 0.12,
      size: 0.0065,
      brightness: 0.55,
      density: 0.7,
      audioFlow: 2.2,
      beatBurst: 1.5,
      sizePulse: 0.7,
      speedColor: 0.04,
      sat: 0.95,
    },
    delta: {
      field: 3,
      attractor: 1,
      ribbon: 0.3,
      midSwirl: 0.55,
      trebleJitter: 0.35,
      saturation: 1.05,
      vignette: 0.5,
      bgLevel: 0.02,
      size: 0.007,
      sat: 0.96,
    },
    sync: { mode: "kick", smooth: 0.28, attack: 0.02, release: 0.45 },
    note: "The description sells a galaxy; curl noise was the only force field available, so what it actually rendered was weather with a centre pull bolted on. `field: 3` (Orbital) plus `attractor: 1` (Ring) is the shape the words already describe. `ribbon` gives the embers streamers instead of dots, and `midSwirl`/`trebleJitter` route two more bands into a look that previously heard only bass and kick. `size` and `sat` move one step each to land on their grids.",
  },
  {
    id: "neon-monsoon",
    name: "Neon Monsoon",
    presetId: "tunnel-rings",
    track: "C2",
    description:
      "A rain-slick tunnel bending through neon — spectrum-lit tiles, drifting color, and a curve that leans into the drums.",
    base: {
      hue: 210,
      hueSpread: 130,
      colorFade: 0.35,
      speed: 1,
      curve: 0.5,
      curveScale: 1.1,
      rings: 11,
      spokes: 18,
      twist: 1.6,
      roundness: 0.7,
      surfaceWarp: 1.2,
      tileSat: 0.9,
      tileSpectrum: 0.55,
      tileLevel: 0.12,
      groutWidth: 0.05,
      groutLevel: 0.26,
      checker: 0.08,
      fogFar: 0.92,
      fogNear: 0.01,
      centerGlow: 0.6,
      beatPulse: 0.9,
      beatBright: 0.3,
      cruiseFloor: 0.5,
      cruiseEnergy: 1.3,
      pulseWidth: 12,
      vignette: 0.3,
    },
    delta: { junction: 0.5, tileSpectrum: 0.56, fogFar: 0.9 },
    sync: { mode: "kick", smooth: 0.26, attack: 0.02, release: 0.45 },
    note: "The thinnest delta in the pass, deliberately. `junction` lights the intersection mouths on the beat, which is pure addition to a look already built around 'leans into the drums'. The other B power for this mode, `material`, is DECLINED: swapping the wall away from tiles changes the entry's silhouette, and the seed's own description names the tiles. `tileSpectrum` and `fogFar` move one step each to land on their grids.",
  },
  {
    id: "solar-temple",
    name: "Solar Temple",
    presetId: "spectrum-scape",
    track: "C2",
    description:
      "A temple of sound rising from an ember moat — every block a frequency band, climbing gold into the dark.",
    base: {
      hue: 285,
      hueRange: 110,
      heightScale: 12,
      camPitch: 34,
      camDist: 20,
      camSpin: -10,
      fov: 58,
      targetY: 1.4,
      emissive: 0.7,
      light: 0.8,
      barWidth: 0.55,
      spacing: 0.75,
    },
    delta: {
      barShape: 2,
      bandGlow: 0.55,
      hotBeat: 0.85,
      glowBeat: 0.7,
      driveHeight: 0.85,
      hotWindow: 0.5,
      fogDensity: 0.06,
      fillLight: 0.45,
      ambientLight: 0.8,
      hueLift: 30,
      saturation: 1.05,
      barWidth: 0.56,
    },
    sync: { mode: "kick", smooth: 0.38, attack: 0.04, release: 0.55, contrast: 0.9 },
    note: "The largest gap of the nine: twelve authored params against a mode that carries twenty-seven after the renderer wave, and none of the fifteen it gained. Everything this entry needed to be a TEMPLE was in that fifteen — `barShape: 2` turns the blocks into round columns, `fillLight`/`ambientLight`/`fogDensity` are the light rig and the haze that make a hall read as depth rather than as a chart, and `hotBeat`/`glowBeat`/`bandGlow`/`driveHeight` give it the beat and band response it had no way to express. `hueLift` climbs the palette with height, which is what 'climbing gold into the dark' means.",
  },
  {
    id: "vhs-sunrise",
    name: "VHS Sunrise",
    presetId: "synthwave",
    track: "C2",
    description:
      "Golden-hour synthwave off a worn tape — big striped sun, teal grid, soft scanlines, mountains in haze.",
    base: {
      hue: 18,
      gridHue: 168,
      sunX: 0.3,
      sunR: 0.3,
      sunY: 0.3,
      sunRays: 0.45,
      scan: 0.75,
      mountains: 0.4,
      gridGlow: 1.3,
      gridScale: 0.7,
      horizonY: 0.5,
      fog: 0.8,
      speed: 1,
      react: 0.9,
      beatPulse: 0.55,
      starDensity: 0.3,
      vignette: 0.3,
    },
    delta: {
      roadW: 0.5,
      roadLanes: 1,
      roadGlow: 0.9,
      skyline: 0.3,
      skyDensity: 0.45,
      windows: 0.3,
      sunWarm: 1.4,
      scanCount: 22,
      scanWidth: 0.55,
      scan: 0.76,
      sunRays: 0.46,
    },
    sync: { mode: "kick", smooth: 0.3, attack: 0.03, release: 0.5 },
    note: "Ten new params arrived on this mode and the seed uses none of them, so it is a sky with nothing underneath it. The road (`roadW`/`roadLanes`/`roadGlow`) is the floor the genre is named for; `skyline`/`skyDensity`/`windows` put a city on the horizon whose lights ride the treble; `sunWarm` and the `scanCount`/`scanWidth` pair turn 'big striped sun' from a fixed sprite into a family you can dial. `scan` and `sunRays` move one step each to land on their grids.",
  },
  {
    id: "obsidian-pulse",
    name: "Obsidian Pulse",
    presetId: "bass-circle",
    track: "C2",
    description:
      "A dark-club bass ring in cold teal — twin mirrored arcs, floating sparks, and a pump you can feel in the artwork.",
    base: {
      hue: 175,
      hueSpread: 40,
      cover: 0,
      radius: 0.16,
      barLen: 0.3,
      gap: 0.05,
      pump: 0.32,
      beatPump: 0.3,
      beatBurst: 1.1,
      particles: 0.8,
      partDensity: 7,
      partFill: 0.4,
      partFloat: 0.6,
      rimBright: 1.25,
      barGlow: 0.5,
      symmetry: 2,
      spin: 0.2,
      saturation: 1.05,
      lightness: 1,
      vignette: 0.5,
    },
    delta: { coreFill: 2, segments: 24, segGap: 0.18, partBeat: 0.45 },
    sync: { mode: "kick", smooth: 0.28, attack: 0.02, release: 0.45 },
    note: "This entry sets `cover: 0` — it is the one seed with a deliberately empty centre, and `coreFill` is the control Track B added for exactly that case. `coreFill: 2` puts a live waveform ring in the hole, so the promise in the description ('a pump you can feel in the artwork') survives on tracks with no artwork at all. `segments` + `segGap` turn the continuous arcs into a VU-style notched ring, which is the club-hardware reading the name already implies, and `partBeat` links the floating sparks to the beat instead of letting them drift independently of it.",
  },
  {
    id: "glass-mandala",
    name: "Glass Mandala",
    presetId: "radial-burst",
    track: "C2",
    description:
      "A wine-dark glass mandala — six flame petals that breathe with the low end, made for slow, heavy sets.",
    base: {
      hue: 305,
      hueSpread: 160,
      symmetry: 6,
      rotSpeed: 0.08,
      innerRadius: 0.22,
      barLen: 0.2,
      coreSize: 0.8,
      glow: 0.4,
      rimBright: 0.85,
      coreBright: 0.4,
      wobBase: 0.04,
      wobAmp: 0.14,
      wobClamp: 0.16,
      spinBase: 0.5,
      spinEnergy: 0.6,
      peaks: 0,
      detailPos: 0.75,
      cover: 0,
      vignette: 0.55,
    },
    delta: {},
    sync: { mode: "bass", smooth: 0.55, attack: 0.2, release: 0.7 },
    note: "The one seed with no parameter delta available: Track B's ranked queue left Radial Burst alone on the grounds that it already IS the bar, so there is nothing new on the mode to reach for. Its whole deepening is the `sync` block — and that is not nothing, because 'breathe with the low end, made for slow, heavy sets' is a statement about response, and the look currently plays at the app default of kick / 0.5 whatever the user last had. Listed as its own row so the owner can see the pass looked at it and found only this.",
  },

  // ---------------------------------------------------------------- C3 ----
  {
    id: "ember-veil",
    name: "Ember Veil",
    presetId: "aurora",
    track: "C3",
    description:
      "Aurora in ember and gold over a moonlit ridge — five curtains, a low moon and a reflection, in the warm half of the palette the mode could not reach before.",
    delta: {
      hue: 28,
      hueStep: 30,
      hueSpread: 85,
      palWarm: 0.7,
      palSpan: 1.25,
      sat: 0.86,
      bright: 1.05,
      react: 0.7,
      flow: 0.55,
      thick: 0.15,
      baseY: 0.46,
      wave: 1.15,
      layers: 5,
      beatPulse: 0.25,
      specAmt: 1.85,
      bassSwell: 0.6,
      drift: 0.35,
      moon: 0.115,
      moonX: -0.42,
      moonY: 0.84,
      moonGlow: 0.52,
      ground: 0.22,
      groundRough: 0.62,
      reflect: 0.34,
      horizon: 0.79,
      reflectFade: 5.5,
      rays: 0.5,
      stars: 1,
      bgGlow: 0.3,
      mirror: 1,
    },
    sync: { mode: "energy", smooth: 0.78, attack: 0.45, release: 0.8 },
    note: "C3's named target, and the reason the v1 seed round dropped Aurora as 'resists scripted tuning' — it did resist, because the palette was a hardcoded cosine basis that `hue` could only ROTATE, so every attempt landed back in the same green-violet family and read as a recolour of the built-in styles. `palWarm` and `palSpan` parameterize the basis itself; this look sits at +0.7 warmth, which is territory no Aurora content has ever occupied. Everything else is the scene the mode gained at the same time and has never shipped in a seed: five curtains instead of three, a low moon with its own halo and placement, a rough landscape silhouette, and the ice reflection under it. Slow envelopes on both edges — this is a look for pads, not for drops.",
  },
  {
    id: "sonar-wall",
    name: "Sonar Wall",
    presetId: "led-matrix",
    track: "C3",
    description:
      "The LED wall running as a scrolling spectrogram: every row is a moment of the track falling away from you, coloured by frequency and lit from behind by the bass.",
    delta: {
      display: 2,
      cols: 64,
      rows: 40,
      gap: 0.09,
      rounded: 0,
      scrollSpeed: 16,
      histFade: 0.55,
      hueLow: 205,
      hueHigh: 305,
      hueShift: 0,
      spectrumColor: 0.9,
      saturation: 1.1,
      lightness: 0.95,
      gradStart: 0.3,
      gradEnd: 0.9,
      litLevel: 0.4,
      dim: 0.1,
      hotBoost: 0.24,
      bassGlow: 0.16,
      beatFlash: 0.22,
      ghost: 0.2,
      peaks: 0,
      peakBright: 0.85,
      bloom: 0.7,
      scanline: 0.16,
      flicker: 0.06,
      panelVariance: 0.3,
      vignette: 0.55,
    },
    sync: { mode: "energy", smooth: 0.4, attack: 0.1, release: 0.45, contrast: 0.55 },
    note: "Waterfall is a display MODE Track B added, not a parameter tweak — a real-time spectrogram scrolling on the texture-feedback path, carrying its history as per-cell data. No shipped look or theme has ever selected it, so the visual exists in the product and has never once been the thing a user sees when they click something. `peaks` is off and `rounded` is off because a waterfall is a continuous surface, not a bar chart; `histFade` and `scrollSpeed` are what set how long the past stays legible.",
  },
  {
    id: "wide-glass",
    name: "Wide Glass",
    presetId: "spectrum-bars",
    track: "C3",
    description:
      "Left channel one way, right channel the other, over a glass floor — a bar wall that shows you how wide your mix actually is.",
    delta: {
      hue: 190,
      hueSpread: 70,
      saturation: 1.05,
      lightness: 1,
      stereoSplit: 0.85,
      capShape: 2,
      reflect: 0.45,
      reflectFade: 4,
      sway: 0.25,
      barGap: 0.3,
      barHeight: 0.7,
      barSat: 0.7,
      barLift: 0.4,
      glow: 0.35,
      glowReach: 8,
      capBright: 1.05,
      peaks: 1,
      mirror: 0,
      beatZoom: 0.02,
      beatFlash: 0.06,
      beatBright: 0.08,
      bgLevel: 0.02,
      bgBassGlow: 0.06,
      freqLo: 0.04,
      freqHi: 0.9,
      vignette: 0.5,
    },
    sync: { mode: "energy", smooth: 0.42, shapeRound: 0.2, contrast: 0.55 },
    note: "`stereoSplit` drives the two halves from the actual stereo field rather than mirroring one signal, which means a mono bounce and a wide master do not look the same — the same class of honesty as the factory pack's one stereo-width route, but on the mode most people meet first. `reflect` + `reflectFade` give it the floor, `capShape: 2` puts dot caps on the peaks, and `freqLo`/`freqHi` trim the span so the bar budget is spent where the music is instead of on empty sub-bass.",
  },
  {
    id: "phase-bloom",
    name: "Phase Bloom",
    presetId: "oscilloscope",
    track: "C3",
    description:
      "A true phase scope: left against right on a crosshair, drawing Lissajous figures out of the stereo image. Rotated 45 degrees, so a mono signal stands upright.",
    delta: {
      hue: 150,
      display: 1,
      xyRotate: 45,
      renderMode: 0,
      traces: 1,
      gain: 1.1,
      calm: 0.5,
      glow: 0.62,
      traceBright: 1.2,
      coreWidth: 0.0025,
      persist: 0.44,
      fill: 0,
      mirror: 0,
      kaleido: 1,
      graticule: 2,
      gridLevel: 0.06,
      gridBeat: 0.35,
      scanline: 0.06,
      beatLift: 0.14,
      hueWave: 30,
      agFloor: 0.3,
      agRange: 1.6,
      bgLevel: 0.02,
      vignette: 0.6,
    },
    sync: { mode: "energy", smooth: 0.35, attack: 0.06, release: 0.4 },
    note: "The XY display is a whole second instrument inside the Oscilloscope mode — planar stereo binding, both channels cut at one shared trigger — and like the waterfall it has never shipped inside anything a user can click. `xyRotate: 45` is the documented convention that stands a mono signal upright, so the figure reads as a phase scope rather than as a diagonal smear, and `graticule: 2` gives it the crosshair a goniometer is supposed to have. Long `persist` because the figure IS the trail.",
  },
];
