/**
 * Timed-lyrics model: parse .lrc / .srt into a flat, sorted line list and
 * resolve the active line for any track time.
 *
 * Everything here is pure and deterministic — the active line is a function
 * of (lines, t) only, which is what lets the live view and the export worker
 * agree frame-for-frame without sharing any state beyond the parsed lines.
 */

export interface LyricLine {
  /** Line start, seconds of track time. */
  t: number;
  /** Explicit end (SRT) or null (LRC — the next line's start ends this one). */
  end: number | null;
  text: string;
  /** Per-word timing from enhanced LRC (A2 `<mm:ss.xx>` tags) — generated by
   * the local pipeline's forced aligner or imported from elsewhere. Absent on
   * plain lines; the karaoke wipe then falls back to linear interpolation.
   * Session-only like the lines themselves: lyrics are NOT serialized into
   * .bfproj (only lyricStyle is), so this additive field needs no
   * PROJECT_VERSION bump — the persistent artifact is the .lrc file. */
  words?: LyricWord[];
  /** Aligner confidence for the line (mean of word confidences, 0..1) —
   * SESSION-ONLY editor metadata. The A2 format cannot carry confidence, so
   * this arrives on the sidecar's result event (never from parsing) and
   * feeds the correction editor's red/amber flags. Absent = no data (an
   * imported file, or the user reviewed the line — edits clear it). */
  conf?: number;
}

/** One timed word. `end` is null when the word runs until the next word's
 * start (the classic A2 contract) — only an explicit `<t>` end marker (our
 * writer's trailing tag, or mid-line end tags from other tools) sets it. */
export interface LyricWord {
  t: number;
  end: number | null;
  text: string;
  /** Aligner confidence 0..1 (peak-relative, see the sidecar). Session-only
   * editor metadata like LyricLine.conf; never parsed from or written to LRC. */
  conf?: number;
}

/** One display style knob-set for the overlay compositor. */
export interface LyricStyle {
  /** 0 = off. */
  enabled: boolean;
  /** Vertical anchor: bottom third (default), center, or top third. */
  position: "bottom" | "center" | "top";
  /** Relative size, 0.5..2 (1 = 4.5% of frame height). */
  size: number;
  /** CSS color for the text. */
  color: string;
  /** Fade in/out at line boundaries, seconds (0 = hard cuts). */
  fadeSec: number;
  /** Entry animation: plain fade, slide-up, or a scale pop. All are driven by
   * the (already frame-keyed) fade alpha, so they stay WYSIWYG. */
  anim?: LyricAnim;
}

export type LyricAnim = "plain" | "slide" | "pop" | "wipe";

export const LYRIC_ANIMS: LyricAnim[] = ["plain", "slide", "pop", "wipe"];

export function isLyricAnim(v: unknown): v is LyricAnim {
  return v === "plain" || v === "slide" || v === "pop" || v === "wipe";
}

export const DEFAULT_LYRIC_STYLE: LyricStyle = {
  enabled: true,
  position: "bottom",
  size: 1,
  color: "#ffffff",
  fadeSec: 0.15,
  anim: "plain",
};

/** Field-by-field validation + defaulting of an untrusted LyricStyle blob.
 * Shared by the localStorage cache and the .bfproj document validator. */
export function validLyricStyle(v: unknown): LyricStyle {
  const raw = (typeof v === "object" && v !== null ? v : {}) as Partial<LyricStyle>;
  const d = DEFAULT_LYRIC_STYLE;
  return {
    enabled: typeof raw.enabled === "boolean" ? raw.enabled : d.enabled,
    position: raw.position === "center" || raw.position === "top" ? raw.position : d.position,
    size:
      typeof raw.size === "number" && Number.isFinite(raw.size)
        ? Math.min(2, Math.max(0.5, raw.size))
        : d.size,
    color:
      typeof raw.color === "string" && /^#[0-9a-f]{3,8}$/i.test(raw.color) ? raw.color : d.color,
    fadeSec:
      typeof raw.fadeSec === "number" && Number.isFinite(raw.fadeSec)
        ? Math.min(1, Math.max(0, raw.fadeSec))
        : d.fadeSec,
    anim: isLyricAnim(raw.anim) ? raw.anim : d.anim,
  };
}

const LRC_TAG = /\[(\d{1,2}):(\d{1,2})(?:[.:](\d{1,3}))?\]/g;
const LRC_META = /^\[(ar|ti|al|by|re|ve|length|au):/i;
const LRC_OFFSET = /^\[offset:\s*([+-]?\d+)\s*\]/i;
/** A2-extension word tag `<mm:ss.xx>` (enhanced LRC). */
const LRC_WORD_TAG = /<(\d{1,2}):(\d{1,2})(?:[.:](\d{1,3}))?>/g;

/** Split a line's text into display text + word timings from A2 `<mm:ss.xx>`
 * tags. The contract (shared with the sidecar's writer, which emits
 * `<t>word <t>word<tEnd>`): each tag starts the word that follows it; a tag
 * followed by nothing (or only whitespace / another tag) is an END marker
 * for the previous word instead — which also covers per-word end tags from
 * other tools. Text before the first tag stays untimed display text.
 * Returns null words when the line carries no tags (plain LRC, unchanged). */
function parseWordTags(
  text: string,
  offsetSec: number,
): { display: string; words: LyricWord[] | null } {
  LRC_WORD_TAG.lastIndex = 0;
  const tags: { t: number; start: number; end: number }[] = [];
  let m: RegExpExecArray | null;
  while ((m = LRC_WORD_TAG.exec(text)) !== null) {
    const frac = m[3] ? Number(m[3]) / Math.pow(10, m[3].length) : 0;
    tags.push({
      t: Math.max(0, Number(m[1]) * 60 + Number(m[2]) + frac + offsetSec),
      start: m.index,
      end: LRC_WORD_TAG.lastIndex,
    });
  }
  const collapse = (s: string) => s.replace(/\s+/g, " ").trim();
  if (tags.length === 0) return { display: collapse(text), words: null };
  const words: LyricWord[] = [];
  let display = text.slice(0, tags[0].start);
  for (let i = 0; i < tags.length; i++) {
    const segEnd = i + 1 < tags.length ? tags[i + 1].start : text.length;
    const seg = text.slice(tags[i].end, segEnd);
    display += seg;
    const wordText = seg.trim();
    if (wordText) {
      words.push({ t: tags[i].t, end: null, text: wordText });
    } else if (words.length > 0 && words[words.length - 1].end === null) {
      words[words.length - 1].end = tags[i].t;
    }
  }
  if (words.length === 0) return { display: collapse(display), words: null };
  // Sanitize untrusted timings so the renderer's math stays simple: word
  // starts never go backwards, an end never precedes its own start.
  for (let i = 1; i < words.length; i++) {
    if (words[i].t < words[i - 1].t) words[i].t = words[i - 1].t;
  }
  for (const w of words) {
    if (w.end !== null && w.end <= w.t) w.end = null;
  }
  return { display: collapse(display), words };
}

/** Parse LRC: `[mm:ss.xx]text`, multiple timestamps per line share the text,
 * a global `[offset:±ms]` shifts everything. Metadata tags are ignored.
 * A2 `<mm:ss.xx>` word tags (enhanced LRC) become per-word timings. */
export function parseLrc(contents: string): LyricLine[] {
  const out: LyricLine[] = [];
  let offsetSec = 0;
  for (const rawLine of contents.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line) continue;
    const off = LRC_OFFSET.exec(line);
    if (off) {
      offsetSec = Number(off[1]) / 1000;
      continue;
    }
    if (LRC_META.test(line)) continue;
    LRC_TAG.lastIndex = 0;
    const stamps: number[] = [];
    let m: RegExpExecArray | null;
    let lastEnd = 0;
    while ((m = LRC_TAG.exec(line)) !== null) {
      // Timestamps must be a contiguous prefix — a "[00:12]" later in the
      // lyric text itself is text, not a tag.
      if (m.index !== lastEnd) break;
      lastEnd = LRC_TAG.lastIndex;
      const frac = m[3] ? Number(m[3]) / Math.pow(10, m[3].length) : 0;
      stamps.push(Number(m[1]) * 60 + Number(m[2]) + frac);
    }
    if (stamps.length === 0) continue;
    const { display, words } = parseWordTags(line.slice(lastEnd), offsetSec);
    if (!display) continue;
    for (const t of stamps) {
      out.push({ t: Math.max(0, t + offsetSec), end: null, text: display });
    }
    if (words) {
      // Word tags are absolute times: on a multi-stamp (repeated-chorus)
      // line they can only belong to ONE of the copies — the latest stamp
      // that still starts at or before the first word (else the earliest).
      const copies = out.slice(out.length - stamps.length);
      const eligible = copies.filter((c) => c.t <= words[0].t + 1e-6);
      const pool = eligible.length > 0 ? eligible : copies;
      let best = pool[0];
      for (const c of pool) {
        if (eligible.length > 0 ? c.t >= best.t : c.t <= best.t) best = c;
      }
      best.words = words;
    }
  }
  return out.sort((a, b) => a.t - b.t);
}

const SRT_TIME =
  /(\d{1,2}):(\d{2}):(\d{2})[,.](\d{1,3})\s*-->\s*(\d{1,2}):(\d{2}):(\d{2})[,.](\d{1,3})/;

/** Parse SRT blocks; multi-line cue text collapses to one line. Basic markup
 * tags (<i>, {\an8}, …) are stripped. */
export function parseSrt(contents: string): LyricLine[] {
  const out: LyricLine[] = [];
  for (const block of contents.split(/\r?\n\r?\n+/)) {
    const lines = block.split(/\r?\n/).filter((l) => l.trim() !== "");
    if (lines.length === 0) continue;
    const timeIdx = lines.findIndex((l) => SRT_TIME.test(l));
    if (timeIdx < 0) continue;
    const tm = SRT_TIME.exec(lines[timeIdx])!;
    const secs = (h: string, m: string, s: string, ms: string) =>
      Number(h) * 3600 + Number(m) * 60 + Number(s) + Number(ms) / Math.pow(10, ms.length);
    const t = secs(tm[1], tm[2], tm[3], tm[4]);
    const end = secs(tm[5], tm[6], tm[7], tm[8]);
    const text = lines
      .slice(timeIdx + 1)
      .join(" ")
      .replace(/<[^>]+>|\{\\[^}]+\}/g, "")
      .trim();
    if (!text || end <= t) continue;
    out.push({ t, end, text });
  }
  return out.sort((a, b) => a.t - b.t);
}

export class LyricParseError extends Error {}

/** Dispatch by extension; unknown extensions try LRC then SRT. Throws when
 * nothing timestamped comes out — a silent empty overlay helps no one. */
export function parseLyrics(fileName: string, contents: string): LyricLine[] {
  const ext = fileName.split(".").pop()?.toLowerCase();
  const lines =
    ext === "srt"
      ? parseSrt(contents)
      : ext === "lrc"
        ? parseLrc(contents)
        : (() => {
            const lrc = parseLrc(contents);
            return lrc.length > 0 ? lrc : parseSrt(contents);
          })();
  if (lines.length === 0) {
    throw new LyricParseError(
      `No timestamped lines found in "${fileName}" — expected .lrc ([mm:ss.xx] …) or .srt`,
    );
  }
  return lines;
}

/**
 * The line active at track time t, or -1. Rightmost line with start <= t;
 * an explicit end (SRT) closes the line early, an implicit one (LRC) runs
 * until the next line starts. Binary search — called every frame.
 */
export function activeLyricIndex(lines: LyricLine[], t: number): number {
  let lo = 0;
  let hi = lines.length - 1;
  let idx = -1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    if (lines[mid].t <= t) {
      idx = mid;
      lo = mid + 1;
    } else {
      hi = mid - 1;
    }
  }
  if (idx < 0) return -1;
  if (lines[idx].end !== null && t >= lines[idx].end!) return -1;
  return idx;
}

/**
 * Alpha for the active line at t, honouring the style's fade window at both
 * boundaries. Pure — same value live and in the export.
 */
export function lyricAlphaAt(lines: LyricLine[], idx: number, t: number, fadeSec: number): number {
  if (idx < 0) return 0;
  if (fadeSec <= 0) return 1;
  const line = lines[idx];
  const start = line.t;
  // Line end: explicit, else the next line's start, else +infinity.
  const end = line.end ?? (idx + 1 < lines.length ? lines[idx + 1].t : Infinity);
  const inA = Math.min(1, (t - start) / fadeSec);
  const outA = end === Infinity ? 1 : Math.min(1, Math.max(0, (end - t) / fadeSec));
  return Math.max(0, Math.min(inA, outA));
}

/**
 * How far the active line has played, 0..1 across its [start, end] window — the
 * karaoke wipe position. Pure (function of lines + t), so live and export agree.
 * An open-ended last line uses a 4 s nominal window so the wipe still completes.
 *
 * With word timing (enhanced LRC), progress follows the REAL words instead of
 * interpolating the whole window: each word contributes its share of the
 * line's characters, filled linearly across that word's own time span (end =
 * explicit end tag, else the next word's start, else the line end). Between a
 * word's explicit end and the next word's start the fill holds. Still a pure
 * function of (lines, t) — word timing changes the shape, not the contract.
 */
export function lyricProgressAt(lines: LyricLine[], idx: number, t: number): number {
  if (idx < 0 || idx >= lines.length) return 0;
  const line = lines[idx];
  const start = line.t;
  const end = line.end ?? (idx + 1 < lines.length ? lines[idx + 1].t : start + 4);
  const words = line.words;
  if (!words || words.length === 0) {
    if (end <= start) return 1;
    return Math.max(0, Math.min(1, (t - start) / (end - start)));
  }
  // Character-weighted spans: word k owns its text plus its leading
  // separator, matching how the draw path measures the sung fraction.
  const totalChars = words.reduce((n, w) => n + w.text.length, 0) + (words.length - 1);
  if (totalChars <= 0) return 0;
  let sung = 0;
  for (let k = 0; k < words.length; k++) {
    const w = words[k];
    const wStart = w.t;
    const wEnd = Math.max(
      wStart + 0.01,
      w.end ?? (k + 1 < words.length ? words[k + 1].t : Math.max(end, wStart)),
    );
    const chars = w.text.length + (k > 0 ? 1 : 0);
    if (t >= wEnd) {
      sung += chars;
      continue;
    }
    if (t > wStart) {
      sung += (chars * (t - wStart)) / (wEnd - wStart);
    }
    break; // words are non-decreasing; nothing later can be sung yet
  }
  return Math.max(0, Math.min(1, sung / totalChars));
}
